---

- hosts: all
  become: true 
  tasks: 

  - name: update and upgrade the servers
    apt:
      update_cache: yes
      upgrade: yes

  - name: set timezone to Africa/Lagos
    tags: time
    timezone: name=Africa/Lagos

  - name: Install apache2 
    tags: apache
    apt:
      name:
        - apache2
      state: latest

  - name: Remove index.hmtl file
    file:
      path: /var/www/html/index.html
      state: absent

  - name: Use the printf script
    shell: 
      cmd: echo "<h1>Welcome. This is public IP address</h1><h2>$(curl ifconfig.me)</h2>" > /var/www/html/index.html
    notify: restart Apache

  handlers:
    - name: restart Apache
      tags: restart
      service:
        name: apache2
        state: restarted